EXTRA_CFLAGS += -I$(src)/inc
EXTRA_CFLAGS += -Werror

snd-soc-tfa98xx-objs += tfa98xx.o
snd-soc-tfa98xx-objs += tfa_container.o
snd-soc-tfa98xx-objs += tfa_dsp.o
snd-soc-tfa98xx-objs += tfa_init.o

obj-$(CONFIG_SND_SOC_TFA98xx) := snd-soc-tfa98xx.o